#!/usr/bin/python3

import sys, os
from PyQt5.QtWidgets import (QApplication, QMainWindow, QTableView,
	QVBoxLayout)
from PyQt5.QtSql import QSqlDatabase, QSqlQuery, QSqlTableModel
from PyQt5.QtCore import Qt
from PyQt5.Qt import QWidget


class main(QMainWindow):
	def __init__(self):
		super().__init__()
		self.setGeometry(50, 50, 640, 480)
		self.createDB()
		self.createTV()

		self.show()

	def createDB(self):
		db_path = os.path.join(os.getcwd(), 'qtv.db')
		if os.path.exists(db_path) and os.path.getsize(db_path) > 0:
			print('Database Exists')
		else:
			db = QSqlDatabase.addDatabase('QSQLITE')
			db.setDatabaseName('qtv.db')

			if not db.open():
				msg = QMessageBox()
				msg.setIcon(QMessageBox.Critical)
				msg.setText("Error in Database Creation")
				retval = msg.exec_()
				return False
			query = QSqlQuery()

			query.exec("create table cowboys(firstname varchar(20), lastname varchar(20))")

			query.exec("insert into cowboys values(101, 'Roy', 'Rogers')")
			query.exec("insert into cowboys values(102, 'Walter', 'Brennan')")
			query.exec("insert into cowboys values(103, 'Lee', 'Marvin')")
			query.exec("insert into cowboys values(104, 'Charles', 'Bronson')")
			query.exec("insert into cowboys values(105, 'Butch', 'Cassidy')")

	def createTV(self):
		db = QSqlDatabase.addDatabase('QSQLITE')
		db.setDatabaseName('qtv.db')
		model = QSqlTableModel()
		model.setTable('cowboys')
		model.setEditStrategy(QSqlTableModel.OnFieldChange)
		model.select()
		model.setHeaderData(0, Qt.Horizontal, "First")
		model.setHeaderData(1, Qt.Horizontal, "Last")
		view = QTableView()
		view.setModel(model)
		view.setWindowTitle("QTableView Example")
		view.clicked.connect(self.getRow)
		layout = QVBoxLayout()
		layout.addWidget(view)
		self.central_widget = QWidget()
		self.setCentralWidget(self.central_widget)


	def getRow(self):
		pass

if __name__ == '__main__':
	app = QApplication(sys.argv)
	gui = main()
	sys.exit(app.exec_())
